name: run-actions
on: [push, pull_request]
jobs:
 run-tests:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Set up Python 3.7
    uses: actions/setup-python@v4
    with:
     python-version: "3.7"
    - name: Install pytest
      run: pip3 install pytest
    - name: Test with Pytest
      run: pytest
